title: Developer Logs
description: "August 2023 to June 2024"
owner_name: Tri3Project
github_username: Tri3Project
github_repo: "DeveloperLogs"
baseurl: "/DeveloperLogs"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/Tri3Project/"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
